name: Run textScript

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          
      - name: Run script
        env:
          TWILIO_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        run: |
          source .venv/bin/activate
          cd Twilio
          python textScript.py


trigger:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger job
        uses: peter-evans/schedule@v2.0.0
        with:
          schedule: '*/1 * * * *'  # trigger every 1 minutes
          job_id: test
          time_zone: America/Chicago