name: Test textScript

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          
      - name: Run script
        with: # Set the secret as an input
          TWILIO_SID: ${{ secrets.twilio_env.SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_ENV.AUTH_TOKEN }}
        env:
          TWILIO_SID: ${{ secrets.twilio_env.SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_ENV.AUTH_TOKEN }}
        run: |
          source .venv/bin/activate
          cd Twilio
          python textScript.py
