name: Test textScript

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          
      - name: Run script
        env:
          TWILIO_ENV: "it's in the env" #${{ secrets.TWILIO_ENV }}
        run: |
          source .venv/bin/activate
          cd Twilio
          export TWILIO_SID=5
          export TWILIO_AUTH_TOKEN='${{ secrets.AUTH_TOKEN }}'
          python textScript.py
